<?php

namespace App\Tests\Task;

use App\Controller\DefaultController;
use App\Entity\Dataset;
use App\Model\DatasetModel;
use App\Tests\TestCase\TaskTestCase;

class StoreTest extends TaskTestCase
{
	protected string $_task = 'Store';

	protected array $_datasets = [];

	public function setUp(): void
	{
		parent::setUp(); // TODO: Change the autogenerated stub

		$dataset = new DatasetModel( new Dataset() );

		$dataset->setName( 'Test ' . microtime() );
		$dataset->setType( '' );
		$dataset->setData( [] );

		$dataset->persist( DefaultController::getEntityManager(), true );

		$this->_datasets = [
			'default' => $dataset,
		];
	}

	public function resetDataset( $dataset ) {
		$dataset->setData( [] );
		$dataset->setType( '' );
		$dataset->persist( $this->getContext()->getEntityManager(), true );
	}

	public function testStore(): void
	{
		$task = $this->getTask();
		$dataset = $this->_datasets['default'];

		// Reset.
		$this->resetDataset( $dataset );

		$data = [
			'name' => 'Test',
			'price' => 12.34,
			'sku' => 'test1',
		];

		$config = [
			'action' => 'set',
			'key' => '',
			'dataset' => $dataset,
		];

		$task->execute( $config, $this->getContext(), $data );

		$result = $dataset->getData();

		$this->assertEquals( $data, $result );

		/**
		 * Get
		 */

		$config['action'] = 'get';

		$getData = $task->execute( $config, $this->getContext(), [] );

		$this->assertEquals( $data, $getData );

		/**
		 * Array type
		 */

		$data = [
			'product' => [
				'name' => 'Test',
				'price' => 12.34,
				'sku' => 'test1',
			],
		];

		$config = [
			'action' => 'set',
			'key' => 'product',
			'dataset' => $dataset,
		];

		$task->execute( $config, $this->getContext(), $data );

		$result = $dataset->getData();

		$this->assertEquals( $data['product'], $result );

		/**
		 * Get
		 */

		$config['action'] = 'get';

		$getData = $task->execute( $config, $this->getContext(), [ 'keepme' => '' ] );

		$this->assertArrayHasKey( 'keepme', $getData );
		$this->assertArrayHasKey( 'product', $getData );
		$this->assertEquals( $data['product'], $getData['product'] );
	}

	public function testStoreFormat(): void
	{
		$task = $this->getTask();
		$dataset = $this->_datasets['default'];

		// Reset.
		$this->resetDataset( $dataset );

		$data = [
			'name' => 'Test',
			'price' => 12.34,
			'sku' => 'test1',
		];

		$config = [
			'action' => 'set',
			'key' => 'sku',
			'dataset' => $dataset,
		];

		$task->execute( $config, $this->getContext(), $data );

		$result = $dataset->getData();

		$this->assertEquals( 'test1', $result );

		/**
		 * Get
		 */

		$config['action'] = 'get';

		$getData = $task->execute( $config, $this->getContext(), [] );

		$this->assertArrayHasKey( 'sku', $getData );
		$this->assertEquals( 'test1', $getData['sku'] );
	}

	public function testStorePath(): void
	{
		$task = $this->getTask();
		$dataset = $this->_datasets['default'];

		// Reset.
		$this->resetDataset( $dataset );

		$data = [
			'name' => 'Test',
			'price' => 12.34,
			'sku' => 'test1',
		];

		$config = [
			'action' => 'set',
			'key' => 'sku',
			'dataset' => $dataset,
			'path' => 'foo.bar'
		];


		$task->execute( $config, $this->getContext(), $data );

		$result = $dataset->getData( 'foo' );

		$this->assertArrayHasKey( 'bar', $result );
		$this->assertEquals( 'test1', $result['bar'] );

		/**
		 * Get
		 */

		$config['action'] = 'get';

		$getData = $task->execute( $config, $this->getContext(), [] );

		$this->assertArrayHasKey( 'sku', $getData );
		$this->assertEquals( 'test1', $getData['sku'] );
	}
}
