<?php

namespace App\Tests\Task;

use App\Controller\DefaultController;
use App\Entity\Dataset;
use App\Model\DatasetModel;
use App\Tests\TestCase\TaskTestCase;

class StoreTest extends TaskTestCase
{
	protected string $_task = 'Store';

	protected array $_datasets = [];

	public function setUp(): void
	{
		parent::setUp(); // TODO: Change the autogenerated stub

		$dataset = new DatasetModel( new Dataset() );

		$dataset->setName( 'Test ' . microtime() );
		$dataset->setType( '' );
		$dataset->setData( [] );

		$dataset->persist( DefaultController::getEntityManager(), true );

		$this->_datasets = [
			'default' => $dataset,
		];
	}

	public function testStore(): void
	{
		$task = $this->getTask();
		$dataset = $this->_datasets['default'];

		$data = [
			'name' => 'Test',
			'price' => 12.34,
			'sku' => 'test1',
		];

		$config = [
			'action' => 'set',
			'key' => 'sku',
			'dataset' => $dataset,
		];

		$task->execute( $config, $this->getContext(), $data );

		$result = $dataset->getData();

		$this->assertEquals( 'test1', $result );

		/**
		 * Get
		 */

		$config = [
			'action' => 'get',
			'key' => 'sku',
			'dataset' => $dataset,
		];

		$getData = $task->execute( $config, $this->getContext(), [] );

		$this->assertArrayHasKey( 'sku', $getData );
		$this->assertEquals( 'test1', $getData['sku'] );
	}
}
