<?php

namespace SyncEngine\Service;

use SyncEngine\Service\Data\ResourceData;

class Conditions
{
	const OPERATOR_SET              = '?';
	const OPERATOR_NOT_SET          = '!?';
	const OPERATOR_EMPTY            = '!';
	const OPERATOR_NOT_EMPTY        = '!!';
	const OPERATOR_IN               = '@'; // '∈'
	const OPERATOR_NOT_IN           = '!@'; // '∉'
	const OPERATOR_IN_STRICT        = '@='; // '∋'
	const OPERATOR_NOT_IN_STRICT    = '!@='; // '∌'
	const OPERATOR_HAS_KEY          = '#';
	const OPERATOR_NOT_HAS_KEY      = '!#';
	const OPERATOR_LESSER           = '<';
	const OPERATOR_GREATER          = '>';
	const OPERATOR_LESSER_OR_EQUAL  = '<=';
	const OPERATOR_GREATER_OR_EQUAL = '>=';
	const OPERATOR_EQUAL            = '==';
	const OPERATOR_NOT_EQUAL        = '!=';
	const OPERATOR_EQUAL_STRICT     = '===';
	const OPERATOR_NOT_EQUAL_STRICT = '!==';
	const OPERATOR_REGEX            = '.*';

	const OPERATORS = [
		self::OPERATOR_SET => self::OPERATOR_SET,
		self::OPERATOR_NOT_SET => self::OPERATOR_NOT_SET,
		self::OPERATOR_EMPTY => self::OPERATOR_EMPTY,
		self::OPERATOR_NOT_EMPTY => self::OPERATOR_NOT_EMPTY,
		self::OPERATOR_IN => self::OPERATOR_IN,
		self::OPERATOR_NOT_IN => self::OPERATOR_NOT_IN,
		self::OPERATOR_IN_STRICT => self::OPERATOR_IN_STRICT,
		self::OPERATOR_NOT_IN_STRICT => self::OPERATOR_NOT_IN_STRICT,
		self::OPERATOR_HAS_KEY => self::OPERATOR_HAS_KEY,
		self::OPERATOR_NOT_HAS_KEY => self::OPERATOR_NOT_HAS_KEY,
		self::OPERATOR_LESSER => self::OPERATOR_LESSER,
		self::OPERATOR_GREATER => self::OPERATOR_GREATER,
		self::OPERATOR_LESSER_OR_EQUAL => self::OPERATOR_LESSER_OR_EQUAL,
		self::OPERATOR_GREATER_OR_EQUAL => self::OPERATOR_GREATER_OR_EQUAL,
		self::OPERATOR_EQUAL => self::OPERATOR_EQUAL,
		self::OPERATOR_NOT_EQUAL => self::OPERATOR_NOT_EQUAL,
		self::OPERATOR_EQUAL_STRICT => self::OPERATOR_EQUAL_STRICT,
		self::OPERATOR_NOT_EQUAL_STRICT => self::OPERATOR_NOT_EQUAL_STRICT,
		self::OPERATOR_REGEX => self::OPERATOR_REGEX,
	];

	public function getOperator( string $operator ): string
	{
		if ( isset( self::OPERATORS[ $operator ] ) ) {
			return $operator;
		}

		return match ( $operator ) {
			'set', 'isset', 'defined' => self::OPERATOR_SET,
			'not_set', 'notset', 'undefined' => self::OPERATOR_NOT_SET,
			'empty' => self::OPERATOR_EMPTY,
			'not_empty', 'notempty' => self::OPERATOR_NOT_EMPTY,
			'in', 'contains' => self::OPERATOR_IN,
			'not_in', 'not_contains' => self::OPERATOR_NOT_IN,
			'in_strict', 'contains_strict' => self::OPERATOR_IN_STRICT,
			'not_in_strict', 'not_contains_strict' => self::OPERATOR_NOT_IN_STRICT,
			'has_key', 'haskey' => self::OPERATOR_HAS_KEY,
			'not_has_key', 'nothaskey' => self::OPERATOR_NOT_HAS_KEY,
			'lt', 'lesser' => self::OPERATOR_LESSER,
			'gt', 'greater' => self::OPERATOR_GREATER,
			'le', 'lesser_or_equal' => self::OPERATOR_LESSER_OR_EQUAL,
			'ge', 'greater_or_equal' => self::OPERATOR_GREATER_OR_EQUAL,
			'eq', 'equal' => self::OPERATOR_EQUAL,
			'ne', 'not_equal' => self::OPERATOR_NOT_EQUAL,
			'eqs', 'equal_strict' => self::OPERATOR_EQUAL_STRICT,
			'nes', 'not_equal_strict' => self::OPERATOR_NOT_EQUAL_STRICT,
			'regex' => self::OPERATOR_REGEX,
		};
	}

	/**
	 * @param  array{ source: mixed, key: mixed, compare: mixed, operator: string }[]  $conditions
	 *
	 * @param  mixed|null                                                              $data
	 *
	 * @return bool
	 */
	public function validate( array $conditions, mixed $data = null ): bool
	{
		// @todo Parse conditions? Currently done in Execute Service.

		foreach ( $conditions as $condition ) {
			if ( ! $condition ) {
				continue;
			}
			if ( ! $this->_validate( $condition, $data ) ) {
				return false;
			}
		}

		return true;
	}

	/**
	 * @param  array{ source: mixed, key: mixed, compare: mixed, operator: string }  $condition
	 *
	 * @param  mixed|null                                                            $data
	 *
	 * @return bool
	 */
	protected function _validate( array $condition, mixed $data = null ): bool
	{
		/**
		 * In case the SOURCE is generated by a tag (storage for example).
		 *
		 * @todo Should we add an extra property "data". Or should we adjust the conditional configs?
		 * @link https://github.com/JoryHogeveen/SyncEngine/issues/91
		 */
		if ( ! empty( $condition['source'] ) ) {
			$data = $condition['source'];
		}

		$key = $condition['key'] ?? '';
		if ( static::isEmptyValue( $key ) ) {

			if ( empty( $condition['operator'] ) ) {
				return true;
			}

			// Direct value comparison.
			$data = [ 'data' => $data ];
			$key  = 'data';
		} elseif ( ! static::isValidKey( $key ) ) {
			/**
			 * In case the KEY is generated by a tag.
			 */
			$data = [ 'data' => $key ];
			$key  = 'data';
		}

		$data = ResourceData::create( $data );

		$compare  = $condition['compare'] ?? null;
		$operator = $this->getOperator( $condition['operator'] ?? null );

		if ( ! $operator ) {
			$operator = ( is_array( $compare ) ) ? self::OPERATOR_IN : self::OPERATOR_EQUAL_STRICT;
		}

		switch ( $operator ) {

			case self::OPERATOR_EQUAL_STRICT:
				return isset( $data[ $key ] ) && $data[ $key ] === $compare;

			case self::OPERATOR_NOT_EQUAL_STRICT:
				return isset( $data[ $key ] ) && $data[ $key ] !== $compare;

			case self::OPERATOR_EQUAL:
				return isset( $data[ $key ] ) && $data[ $key ] == $compare;

			case self::OPERATOR_NOT_EQUAL:
				return isset( $data[ $key ] ) && $data[ $key ] != $compare;

			case self::OPERATOR_SET:
				return isset( $data[ $key ] );

			case self::OPERATOR_NOT_SET:
				return ! isset( $data[ $key ] );

			case self::OPERATOR_EMPTY:
				return empty( $data[ $key ] );

			case self::OPERATOR_NOT_EMPTY:
				return ! empty( $data[ $key ] );

			case self::OPERATOR_IN:
				if ( isset( $data[ $key ] ) ) {
					if ( is_array( $data[ $key ] ) ) {
						return in_array( $compare, $data[ $key ] );
					}

					return str_contains( $data[ $key ], $compare );
				}

				return false;

			case self::OPERATOR_NOT_IN:
				if ( isset( $data[ $key ] ) ) {
					if ( is_array( $data[ $key ] ) ) {
						return ! in_array( $compare, $data[ $key ] );
					}

					return ! str_contains( $data[ $key ], $compare );
				}

				return true;

			case self::OPERATOR_IN_STRICT:
				if ( isset( $data[ $key ] ) ) {
					if ( is_array( $data[ $key ] ) ) {
						return in_array( $compare, $data[ $key ], true );
					}

					return $this->strContainsStrict( $data[ $key ], $compare );
				}

				return false;

			case self::OPERATOR_NOT_IN_STRICT:
				if ( isset( $data[ $key ] ) ) {
					if ( is_array( $data[ $key ] ) ) {
						return ! in_array( $compare, $data[ $key ], true );
					}

					return ! $this->strContainsStrict( $data[ $key ], $compare );
				}

				return true;

			case self::OPERATOR_HAS_KEY:
				if ( ! static::isValidKey( $compare ) ) {
					return false;
				}

				// Check value first.
				$value = $data[ $key ] ?? null;
				if ( ! $value ) {
					return false;
				}

				return isset( $value[ $compare ] );

			case self::OPERATOR_NOT_HAS_KEY:
				if ( ! static::isValidKey( $compare ) ) {
					return true;
				}

				// Check value first.
				$value = $data[ $key ] ?? null;
				if ( ! $value ) {
					// @todo Error?
					return true;
				}

				return ! isset( $value[ $compare ] );

			case self::OPERATOR_LESSER:
				return isset( $data[ $key ] ) && $data[ $key ] < $compare;

			case self::OPERATOR_GREATER:
				return isset( $data[ $key ] ) && $data[ $key ] > $compare;

			case self::OPERATOR_LESSER_OR_EQUAL:
				return isset( $data[ $key ] ) && $data[ $key ] <= $compare;

			case self::OPERATOR_GREATER_OR_EQUAL:
				return isset( $data[ $key ] ) && $data[ $key ] >= $compare;

			case self::OPERATOR_REGEX:
				return isset( $data[ $key ] ) && preg_match( $compare, $data[ $key ] );
		}

		return false;
	}

	public static function isEmptyValue( mixed $value ): bool
	{
		return empty( $value ) && ! is_numeric( $value );
	}

	public static function isValidKey( mixed $value ): bool
	{
		return is_string( $value ) || is_numeric( $value );
	}

	private function strContainsStrict( string $haystack, string $needle ): bool
	{
		// Custom word boundary that allows underscores to be detected as word separators.
		return (bool) preg_match( "~(?:\b|_\K)({$needle})(?=\b|_)~", $haystack );
	}
}
