<?php

namespace SyncEngine\Service;

class Conditions
{
	public function validate( array $conditions, mixed $data = null ): bool
	{
		// @todo Parse conditions? Currently done in Execute Service.

		foreach ( $conditions as $condition ) {
			if ( ! $condition ) {
				continue;
			}
			if ( ! $this->_validate( $condition, $data ) ) {
				return false;
			}
		}

		return true;
	}

	protected function _validate( array $condition, mixed $data = null ): bool
	{
		/**
		 * In case the SOURCE is generated by a tag (storage for example).
		 *
		 * @todo Should we add an extra property "data". Or should we adjust the conditional configs?
		 * @link https://github.com/JoryHogeveen/SyncEngine/issues/91
		 */
		if ( ! empty( $condition['source'] ) && is_iterable( $condition['source'] ) ) {
			$data = $condition['source'];
		}

		$key = $condition['key'] ?? '';
		if ( ! $key ) {

			if ( empty( $condition['operator'] ) ) {
				return true;
			}

			// Direct value comparison.
			$data = [ 'data' => $data ];
			$key  = 'data';

		} elseif ( is_array( $key ) ) {
			/**
			 * In case the KEY is generated by a tag.
			 */
			$data = [ 'data' => $key ];
			$key  = 'data';
		}

		$data = ResourceData::create( $data );

		$compare  = $condition['compare'] ?? null;
		$operator = $condition['operator'] ?? null;

		if ( ! $operator ) {
			$operator = ( is_array( $compare ) ) ? 'in' : 'default';
		}

		switch ( $operator ) {
			case 'set':
				return isset( $data[ $key ] );
			case 'not_set':
				return ! isset( $data[ $key ] );
			case 'empty':
				return empty( $data[ $key ] );
			case 'not_empty':
				return ! empty( $data[ $key ] );
			case 'in':
				if ( isset( $data[ $key ] ) ) {
					if ( is_array( $data[ $key ] ) ) {
						return in_array( $compare, $data[ $key ] );
					}

					return str_contains( $data[ $key ], $compare );
				}

				return false;
			case 'not':
				if ( isset( $data[ $key ] ) ) {
					if ( is_array( $data[ $key ] ) ) {
						return ! in_array( $compare, $data[ $key ] );
					}

					return ! str_contains( $data[ $key ], $compare );
				}

				return true;
			case 'in_strict':
				if ( isset( $data[ $key ] ) ) {
					if ( is_array( $data[ $key ] ) ) {
						return in_array( $compare, $data[ $key ], true );
					}

					return str_contains( $data[ $key ], $compare );
				}

				return false;
			case 'not_strict':
				if ( isset( $data[ $key ] ) ) {
					if ( is_array( $data[ $key ] ) ) {
						return ! in_array( $compare, $data[ $key ], true );
					}

					return ! str_contains( $data[ $key ], $compare );
				}

				return true;
			case 'haskey':
			case 'has_key':
				if ( ! is_string( $compare ) && ! is_numeric( $compare ) ) {
					return false;
				}

				// Check value first.
				$value = $data[ $key ] ?? null;
				if ( ! $value ) {
					return false;
				}

				return isset( $value[ $compare ] );
			case 'nothaskey':
			case 'not_has_key':
				if ( ! is_string( $compare ) && ! is_numeric( $compare ) ) {
					return true;
				}

				// Check value first.
				$value = $data[ $key ] ?? null;
				if ( ! $value ) {
					// @todo Error?
					return true;
				}

				return ! isset( $value[ $compare ] );
			case '<':
				return $compare < $data[ $key ];
			case '>':
				return $compare > $data[ $key ];
			case '<=':
				return $compare <= $data[ $key ];
			case '>=':
				return $compare >= $data[ $key ];
			case '!=':
				return $compare != $data[ $key ];
			case '==':
				return $compare == $data[ $key ];
			case '!==':
				return $compare !== $data[ $key ];
			case '===':
			default:
				return $compare === $data[ $key ];
		}
	}
}
