<?php

namespace SyncEngine\Service;

class Conditions
{
	const OPERATOR_SET              = '?';
	const OPERATOR_NOT_SET          = '!?';
	const OPERATOR_EMPTY            = '!';
	const OPERATOR_NOT_EMPTY        = '!!';
	const OPERATOR_IN               = '@'; // '∈'
	const OPERATOR_NOT_IN           = '!@'; // '∉'
	const OPERATOR_IN_STRICT        = '@='; // '∋'
	const OPERATOR_NOT_IN_STRICT    = '!@='; // '∌'
	const OPERATOR_HAS_KEY          = '#';
	const OPERATOR_NOT_HAS_KEY      = '!#';
	const OPERATOR_LESSER           = '<';
	const OPERATOR_GREATER          = '>';
	const OPERATOR_LESSER_OR_EQUAL  = '<=';
	const OPERATOR_GREATER_OR_EQUAL = '>=';
	const OPERATOR_NOT_EQUAL        = '!=';
	const OPERATOR_EQUAL            = '==';
	const OPERATOR_NOT_EQUAL_STRICT = '!==';
	const OPERATOR_EQUAL_STRICT     = '===';

	const OPERATORS = [
		self::OPERATOR_SET,
		self::OPERATOR_NOT_SET,
		self::OPERATOR_EMPTY,
		self::OPERATOR_NOT_EMPTY,
		self::OPERATOR_IN,
		self::OPERATOR_NOT_IN,
		self::OPERATOR_IN_STRICT,
		self::OPERATOR_NOT_IN_STRICT,
		self::OPERATOR_HAS_KEY,
		self::OPERATOR_NOT_HAS_KEY,
		self::OPERATOR_LESSER,
		self::OPERATOR_GREATER,
		self::OPERATOR_LESSER_OR_EQUAL,
		self::OPERATOR_GREATER_OR_EQUAL,
		self::OPERATOR_NOT_EQUAL,
		self::OPERATOR_EQUAL,
		self::OPERATOR_NOT_EQUAL_STRICT,
		self::OPERATOR_EQUAL_STRICT,
	];

	public function getOperator( string $operator ): string
	{
		return match ( $operator ) {
			'set', 'isset', 'defined' => self::OPERATOR_SET,
			'not_set', 'notset', 'undefined' => self::OPERATOR_NOT_SET,
			'empty' => self::OPERATOR_EMPTY,
			'not_empty', 'notempty' => self::OPERATOR_NOT_EMPTY,
			'in' => self::OPERATOR_IN,
			'not', 'not_in', 'nin' => self::OPERATOR_NOT_IN,
			'ins', 'in_strict' => self::OPERATOR_IN_STRICT,
			'nins', 'not_in_strict' => self::OPERATOR_NOT_IN_STRICT,
			'has', 'has_key', 'haskey' => self::OPERATOR_HAS_KEY,
			'nhas', 'not_has', 'nothas', 'not_has_key', 'nothaskey' => self::OPERATOR_NOT_HAS_KEY,
			'lt', 'lesser' => self::OPERATOR_LESSER,
			'gt', 'greater' => self::OPERATOR_GREATER,
			'le', 'lesser_or_equal' => self::OPERATOR_LESSER_OR_EQUAL,
			'ge', 'greater_or_equal' => self::OPERATOR_GREATER_OR_EQUAL,
			'ne', 'not_equal' => self::OPERATOR_NOT_EQUAL,
			'eq', 'equal' => self::OPERATOR_EQUAL,
			'nes', 'not_equal_strict' => self::OPERATOR_NOT_EQUAL_STRICT,
			'eqs', 'equal_strict' => self::OPERATOR_EQUAL_STRICT,
			default => $operator,
		};
	}

	public function validate( array $conditions, mixed $data = null ): bool
	{
		// @todo Parse conditions? Currently done in Execute Service.

		foreach ( $conditions as $condition ) {
			if ( ! $condition ) {
				continue;
			}
			if ( ! $this->_validate( $condition, $data ) ) {
				return false;
			}
		}

		return true;
	}

	protected function _validate( array $condition, mixed $data = null ): bool
	{
		/**
		 * In case the SOURCE is generated by a tag (storage for example).
		 *
		 * @todo Should we add an extra property "data". Or should we adjust the conditional configs?
		 * @link https://github.com/JoryHogeveen/SyncEngine/issues/91
		 */
		if ( ! empty( $condition['source'] ) ) {
			$data = $condition['source'];
		}

		$key = $condition['key'] ?? '';
		if ( ! $key ) {

			if ( empty( $condition['operator'] ) ) {
				return true;
			}

			// Direct value comparison.
			$data = [ 'data' => $data ];
			$key  = 'data';
		} elseif ( is_array( $key ) ) {
			/**
			 * In case the KEY is generated by a tag.
			 */
			$data = [ 'data' => $key ];
			$key  = 'data';
		}

		$data = ResourceData::create( $data );

		$compare  = $condition['compare'] ?? null;
		$operator = $this->getOperator( $condition['operator'] ?? null );

		if ( ! $operator ) {
			$operator = ( is_array( $compare ) ) ? self::OPERATOR_IN : 'default';
		}

		switch ( $operator ) {

			case self::OPERATOR_SET:
				return isset( $data[ $key ] );

			case self::OPERATOR_NOT_SET:
				return ! isset( $data[ $key ] );

			case self::OPERATOR_EMPTY:
				return empty( $data[ $key ] );

			case self::OPERATOR_NOT_EMPTY:
				return ! empty( $data[ $key ] );

			case self::OPERATOR_IN:
				if ( isset( $data[ $key ] ) ) {
					if ( is_array( $data[ $key ] ) ) {
						return in_array( $compare, $data[ $key ] );
					}

					return str_contains( $data[ $key ], $compare );
				}

				return false;

			case self::OPERATOR_NOT_IN:
				if ( isset( $data[ $key ] ) ) {
					if ( is_array( $data[ $key ] ) ) {
						return ! in_array( $compare, $data[ $key ] );
					}

					return ! str_contains( $data[ $key ], $compare );
				}

				return true;

			case self::OPERATOR_IN_STRICT:
				if ( isset( $data[ $key ] ) ) {
					if ( is_array( $data[ $key ] ) ) {
						return in_array( $compare, $data[ $key ], true );
					}

					return str_contains( $data[ $key ], $compare );
				}

				return false;

			case self::OPERATOR_NOT_IN_STRICT:
				if ( isset( $data[ $key ] ) ) {
					if ( is_array( $data[ $key ] ) ) {
						return ! in_array( $compare, $data[ $key ], true );
					}

					return ! str_contains( $data[ $key ], $compare );
				}

				return true;

			case self::OPERATOR_HAS_KEY:
				if ( ! is_string( $compare ) && ! is_numeric( $compare ) ) {
					return false;
				}

				// Check value first.
				$value = $data[ $key ] ?? null;
				if ( ! $value ) {
					return false;
				}

				return isset( $value[ $compare ] );

			case self::OPERATOR_NOT_HAS_KEY:
				if ( ! is_string( $compare ) && ! is_numeric( $compare ) ) {
					return true;
				}

				// Check value first.
				$value = $data[ $key ] ?? null;
				if ( ! $value ) {
					// @todo Error?
					return true;
				}

				return ! isset( $value[ $compare ] );

			case self::OPERATOR_LESSER:
				return $compare < $data[ $key ];

			case self::OPERATOR_GREATER:
				return $compare > $data[ $key ];

			case self::OPERATOR_LESSER_OR_EQUAL:
				return $compare <= $data[ $key ];

			case self::OPERATOR_GREATER_OR_EQUAL:
				return $compare >= $data[ $key ];

			case self::OPERATOR_NOT_EQUAL:
				return $compare != $data[ $key ];

			case self::OPERATOR_EQUAL:
				return $compare == $data[ $key ];

			case self::OPERATOR_NOT_EQUAL_STRICT:
				return $compare !== $data[ $key ];

			case self::OPERATOR_EQUAL_STRICT:
			default:
				return $compare === $data[ $key ];
		}
	}
}
