<?php

namespace App\Service;

use App\Controller\DefaultController;
use App\Entity\Automation;
use App\Entity\Flow;
use App\Entity\Step;
use App\Message\AutomationLooper;
use App\Model\AutomationModel;
use App\Model\FlowModel;
use App\Model\StepModel;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Messenger\MessageBusInterface;

class ExecutePreview extends Execute
{
	const MODE_SAFE = 'safe';
	const MODE_LIVE = 'live';

	protected array $scope;
	protected object $testModel;
	protected array $testConfig;

	public function schedule( AutomationModel $automation ): void
	{
		// Nope.
	}

	public function preview( array $scope, ExecutionContext $context ): array
	{
		$this->scope = $scope;

		$mode = $scope['mode'] ?? self::MODE_SAFE;
		$context->setPreviewMode( $mode );

		$this->scope['automation'] = $scope['automation'] ? AutomationModel::get( $scope['automation'] ) : null;
		$this->scope['flow']       = $scope['flow'] ? FlowModel::get( $scope['flow'] ) : null;
		$this->scope['step']       = $scope['step'] ? StepModel::get( $scope['step'] ) : null;

		$data   = $scope['data'];
		$ref    = $scope['ref'];
		$config = $scope['config'];

		$this->testConfig = $config;

		switch ( $scope['type'] ) {
			case 'task':
				if ( $this->scope['automation'] ) {
					$return = $this->execute( $this->scope['automation'], $context, $data );
				} elseif ( $this->scope['flow'] ) {
					$return = $this->executeFlow( $this->scope['flow'], $context, $data );
				} elseif ( $this->scope['step'] ) {
					$return = $this->executeStep( $this->scope['step'], $context, $data );
				} else {
					$return = $this->executeTask( $config, $context, $data );
				}
				break;
			case 'step':
				$step = new StepModel( new Step() );
				$step->setConfig( $config );
				$step->setRef( $ref );

				$this->testModel = $step;

				if ( $this->scope['automation'] ) {
					$return = $this->execute( $this->scope['automation'], $context, $data );
				} elseif ( $this->scope['flow'] ) {
					$return = $this->executeFlow( $this->scope['flow'], $context, $data );
				} else {
					$return = $this->executeStep( $step, $context, $data );
				}
				break;
			case 'flow':
				$flow = new FlowModel( new Flow() );
				$flow->setConfig( $config );
				$flow->setRef( $ref );

				$this->testModel = $flow;

				if ( $this->scope['automation'] ) {
					$return = $this->execute( $this->scope['automation'], $context, $data );
				} else {
					$return = $this->executeFlow( $flow, $context, $data );
				}
				break;
			case 'automation':
				$automation = new AutomationModel( new Automation() );
				$automation->setConfig( $config );
				$automation->setRef( $ref );

				$this->testModel = $automation;

				$return = $this->execute( $automation, $context, $data );
				break;
			default:
				$context->addError( 'No preview scope set' );
				break;
		}

		$errors = $context->getErrors();
		if ( $errors ) {
			return [
				'success' => false,
				'errors'  => $errors,
			];
		}

		return [
			'success' => true,
			'data'    => $return ?? [],
		];
	}

	public function isCurrentScope( ExecutionContext $context, $current ) {
		static $done;
		if ( $done ) {
			return true;
		}

		if ( $this->scope['automation'] && $this->scope['automation']->getId() !== $context->getAutomation()->getId() ) {
			return false;
		}
		if ( $this->scope['flow'] && $this->scope['flow']->getId() !== $context->getCurrentFlow()->getId() ) {
			return false;
		}
		if ( $this->scope['step'] && $this->scope['step']->getId() !== $context->getCurrentStep()->getId() ) {
			return false;
		}
		if ( isset( $this->testConfig['_ref'] ) && $this->testConfig['_ref'] !== $current['_ref'] ) {
			return false;
		}

		$done = true;
		return true;
	}

	public function execute( AutomationModel $automation, ExecutionContext $context, $data = null ): array
	{
		$automation->endIterator();
		$data = $this->fetch( $automation, $context, $data );

		$return = $data;
		if ( $data ) {
			$flow = FlowModel::get( $automation->getFlow() );
			if ( $flow ) {
				try {
					$return = $this->executeFlow( $flow, $context, $data );
				} catch ( \Throwable $e ) {
					$data = [];
					$context->addError( $e );
				}
			}
		} else {
			$context->addError( 'No data found' );
		}

		return $return ?? [];
	}

	public function executeFlow( FlowModel $flow, ExecutionContext $context, $data ): array
	{
		if ( $this->isCurrentScope( $context, $flow ) ) {
			// Previous loop sets the scope, if it's the current do not continue.
			return $data;
		}

		return parent::executeFlow( $flow, $context, $data ); // TODO: Change the autogenerated stub
	}

	public function executeStep( StepModel $step, ExecutionContext $context, $data ): array
	{
		if ( $this->isCurrentScope( $context, $step ) ) {
			// Previous loop sets the scope, if it's the current do not continue.
			return $data;
		}

		return parent::executeStep( $step, $context, $data ); // TODO: Change the autogenerated stub
	}

	public function executeTask( array $config, ExecutionContext $context, $data ): array
	{
		if ( $this->isCurrentScope( $context, $config ) ) {
			// Previous loop sets the scope, if it's the current do not continue.
			// In the case of a task the current scope is determined by the config ref.
			// For this reason we still need to execute the current task.
			return parent::executeTask( $config, $context, $data );
		}

		$task = $config['_class'] ?? '';
		if ( $task ) {
			if ( 'Send' === $task && self::MODE_LIVE !== $context->getPreviewMode() ) {
				return $data;
			}
			parent::executeTask( $config, $context, $data );
		}

		return $data;
	}
}
