twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        '%syncengine.dir.modules%': SyncEngineModules
    globals:
        __expirimental: '%syncengine.__experimental%'
        icons: '%syncengine.icons%'
        meta:
            title: '%syncengine.meta.title%'

when@test:
    twig:
        strict_variables: true
