twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
      - 'bootstrap_5_layout.html.twig'
      - '_partials/form/bootstrap_5_form_columns_layout.html.twig'
    paths:
        '%syncengine.dir.modules%': SyncEngineModules
    globals:
        __experimental: '%syncengine.__experimental%'
        icons: '%syncengine.icons%'
        meta:
            title: '%syncengine.meta.title%'

when@test:
    twig:
        strict_variables: true
