<?php

namespace SyncEngine\Column;

use SyncEngine\Column\Type\TextColumnType;
use SyncEngine\Model\ColumnModel;
use SyncEngine\Service\Format\DateTimeFormatter;
use SyncEngine\Service\Interface\FormatInterface;

class DateTime extends ColumnModel
{
	public function __construct()
	{
		parent::__construct();

		$this->type        = TextColumnType::TYPE;
		$this->name        = $this->trans( 'Date' );
		$this->description = $this->trans( 'General date and time column' );
	}

	public function getFields(): array
	{
		return [
			'format'   => [
				'label'    => $this->trans( 'Format' ),
				'help'     => $this->trans( 'Please check PHP date documentation' ),
				'type'     => 'text',
				'required' => true,
			],
			'timezone' => [
				'label' => $this->trans( 'Timezone' ),
				'help'  => $this->trans( 'Please check PHP DateTimeZone documentation' ),
				'type'  => 'text',
			],
			'empty'    => [
				'label'        => $this->trans( 'Empty value' ),
				'type'         => 'select',
				'customizable' => true,
				'choices'      => [
					''            => $this->trans( 'Unchanged' ),
					'{*null*}'    => $this->trans( 'Null' ),
					'{*boolean*}' => $this->trans( 'False' ),
					'{*string*}'  => $this->trans( 'Empty string' ),
					'{*now*}'     => $this->trans( 'Current timestamp format' ),
				],
			],
		];
	}

	public function format( $value, ?array $config = null, ?ColumnModel $source = null )
	{
		if ( empty( $value ) ) {
			switch ( $config['empty'] ?? '' ) {
				case '{*null*}':
					return null;
				case '{*boolean*}':
					return false;
				case '{*string*}':
					return '';
				case '{*now*}':
					$value = time();
				break;
				default:
					if ( ! empty( $config['empty'] ) ) {
						return $config['empty'];
					}

					return $value;
			}
		}

		return parent::format( $value, $config, $source ); // TODO: Change the autogenerated stub
	}

	public function initFormatter( $config = [] ): FormatInterface
	{
		$context = [
			DateTimeFormatter::FORMAT   => $config['format'],
			DateTimeFormatter::TIMEZONE => $config['timezone'] ?? null,
		];

		return new DateTimeFormatter( $context );
	}
}
