<?php

return [
	[
		'id' => 'welcome',
		'target' => null,
		'title' => 'onboarding.dashboard.welcome.title',
		'body' => 'onboarding.dashboard.welcome.body',
		'type' => 'modal',
		'placement' => 'center',
	],
	[
		'id' => 'menu',
		'target' => '#menu',
		'title' => 'onboarding.dashboard.menu.title',
		'body' => 'onboarding.dashboard.menu.body',
		'type' => 'popover',
		'placement' => 'right',
	],
	[
		'id' => 'connections',
		'target' => '#menu-syncengine_connection_list',
		'title' => 'onboarding.dashboard.connections.title',
		'body' => 'onboarding.dashboard.connections.body',
		'type' => 'popover',
		'placement' => 'right',
		'doc_url' => 'https://docs.syncengine.io/user/connections/',
	],
	[
		'id' => 'automations',
		'target' => '#menu-syncengine_automation_list',
		'title' => 'onboarding.dashboard.automations.title',
		'body' => 'onboarding.dashboard.automations.body',
		'type' => 'popover',
		'placement' => 'right',
		'doc_url' => 'https://docs.syncengine.io/user/automations/',
	],
	[
		'id' => 'flows',
		'target' => '#menu-syncengine_flow_list',
		'title' => 'onboarding.dashboard.flows.title',
		'body' => 'onboarding.dashboard.flows.body',
		'type' => 'popover',
		'placement' => 'right',
		'doc_url' => 'https://docs.syncengine.io/user/flows/',
	],
	[
		'id' => 'routines',
		'target' => '#menu-syncengine_routine_list',
		'title' => 'onboarding.dashboard.routines.title',
		'body' => 'onboarding.dashboard.routines.body',
		'type' => 'popover',
		'placement' => 'right',
		'doc_url' => 'https://docs.syncengine.io/user/routines/',
	],
	[
		'id' => 'storages',
		'target' => '#menu-syncengine_storage_list',
		'title' => 'onboarding.dashboard.storages.title',
		'body' => 'onboarding.dashboard.storages.body',
		'type' => 'popover',
		'placement' => 'right',
		'doc_url' => 'https://docs.syncengine.io/user/storages/',
	],
	[
		'id' => 'modules',
		'target' => '#menu-syncengine_modules',
		'title' => 'onboarding.dashboard.modules.title',
		'body' => 'onboarding.dashboard.modules.body',
		'type' => 'popover',
		'placement' => 'right',
	],
	[
		'id' => 'runtime-history',
		'target' => '#runtime_history',
		'title' => 'onboarding.dashboard.runtime_history.title',
		'body' => 'onboarding.dashboard.runtime_history.body',
		'type' => 'popover',
		'placement' => 'center',
	],
	[
		'id' => 'summary',
		'target' => null,
		'title' => 'onboarding.dashboard.summary.title',
		'body' => 'onboarding.dashboard.summary.body',
		'type' => 'modal',
		'placement' => 'center',
		'doc_url' => 'https://docs.syncengine.io/user/best-practices/'
	],
	[
		'id' => 'help-icon',
		'target' => '#onboarding-help',
		'title' => 'onboarding.dashboard.help.title',
		'body' => 'onboarding.dashboard.help.body',
		'type' => 'popover',
		'placement' => 'bottom',
	],
];
