<?php

namespace SyncEngine\Tests\Runtime\Preview;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use SyncEngine\Controller\SandboxController;
use SyncEngine\Runtime\ExecutePreview;
use SyncEngine\Tests\TestCase\RuntimeScenarioTestCase;

class SandboxControllerPreviewTest extends RuntimeScenarioTestCase
{
	public function setUp(): void
	{
		self::bootKernel();

		static::getContainer()->get( SandboxController::class )->setContainer( SandboxController::getContainer() );

		parent::setUp(); // TODO: Change the autogenerated stub
	}

	protected function createController(): SandboxController
	{
		return static::getContainer()->get( SandboxController::class );
	}

	protected function callHandlePreview( SandboxController $controller, Request $request, ExecutePreview $executePreview ): \Symfony\Component\HttpFoundation\JsonResponse
	{
		$method = new \ReflectionMethod( $controller, 'handlePreview' );
		$method->setAccessible( true );
		return $method->invoke( $controller, $request, $executePreview );
	}

	public function testPreviewWithInvalidJsonReturnsBadRequest(): void
	{
		$controller = $this->createController();
		$request = new Request( content: 'not valid json {{{' );

		$executePreview = static::getContainer()->get( ExecutePreview::class );
		$response = $this->callHandlePreview( $controller, $request, $executePreview );

		$this->assertSame( Response::HTTP_BAD_REQUEST, $response->getStatusCode() );
		$data = json_decode( $response->getContent(), true );
		$this->assertFalse( $data['success'] );
		$this->assertStringContainsString( 'Invalid JSON', $data['message'] );
	}

	public function testPreviewWithInvalidTypeReturnsBadRequest(): void
	{
		$controller = $this->createController();
		$request = new Request( content: json_encode( [ 'type' => 'invalid_type', 'config' => [] ] ) );

		$executePreview = static::getContainer()->get( ExecutePreview::class );
		$response = $this->callHandlePreview( $controller, $request, $executePreview );

		$this->assertSame( Response::HTTP_BAD_REQUEST, $response->getStatusCode() );
		$data = json_decode( $response->getContent(), true );
		$this->assertFalse( $data['success'] );
		$this->assertArrayHasKey( 'valid_types', $data );
		$this->assertIsArray( $data['valid_types'] );
	}

	public function testPreviewWithValidTaskTypeSucceeds(): void
	{
		$controller = $this->createController();
		$request = new Request(
			content: json_encode( [
				'type' => 'task',
				'config' => [
					'_class' => 'Set',
					'_ref' => 'test',
					'params' => [ [ 'key' => 'test', 'value' => 'ok' ] ] // Required
				],
			] )
		);

		$executePreview = static::getContainer()->get( ExecutePreview::class );
		$response = $this->callHandlePreview( $controller, $request, $executePreview );

		$this->assertSame( Response::HTTP_OK, $response->getStatusCode() );
		$data = json_decode( $response->getContent(), true );
		$this->assertTrue( $data['success'] );
		$this->assertArrayHasKey( 'data', $data );
	}

	public function testPreviewWithValidRoutineTypeSucceeds(): void
	{
		$controller = $this->createController();

		$request = new Request(
			content: json_encode( [
				'type' => 'routine',
				'config' => [ '_ref' => 'test_routine_task', 'tasks' => [] ],
			] )
		);

		$executePreview = static::getContainer()->get( ExecutePreview::class );
		$response = $this->callHandlePreview( $controller, $request, $executePreview );

		$this->assertSame( Response::HTTP_OK, $response->getStatusCode() );
		$data = json_decode( $response->getContent(), true );
		$this->assertTrue( $data['success'] );
	}

	public function testPreviewWithValidStepTypeButMissingRoutineFails(): void
	{
		$controller = $this->createController();
		$request = new Request(
			content: json_encode( [
				'type' => 'step',
				'config' => [ '_ref' => 'test_step' ],
			] )
		);

		$executePreview = static::getContainer()->get( ExecutePreview::class );
		$response = $this->callHandlePreview( $controller, $request, $executePreview );

		$result = json_decode( $response->getContent(), true );

		$this->assertSame( Response::HTTP_PARTIAL_CONTENT, $response->getStatusCode() );
		$this->assertFalse( $result['success'] );
		$this->assertStringContainsString( 'Routine', $result['data']['Errors'][0]['message'] );
	}

	public function testPreviewWithValidFlowTypeSucceeds(): void
	{
		$controller = $this->createController();
		$request = new Request(
			content: json_encode( [
				'type' => 'flow',
				'config' => [ '_ref' => 'test_flow', 'steps' => [] ],
			] )
		);

		$executePreview = static::getContainer()->get( ExecutePreview::class );
		$response = $this->callHandlePreview( $controller, $request, $executePreview );

		$this->assertSame( Response::HTTP_OK, $response->getStatusCode() );
		$data = json_decode( $response->getContent(), true );
		$this->assertTrue( $data['success'] );
	}

	public function testPreviewWithValidAutomationTypeSucceeds(): void
	{
		$controller = $this->createController();
		$request = new Request(
			content: json_encode( [
				'type' => 'automation',
				'config' => [ 'request' => [], 'actions' => [] ],
			] )
		);

		$executePreview = static::getContainer()->get( ExecutePreview::class );
		$response = $this->callHandlePreview( $controller, $request, $executePreview );

		$this->assertSame( Response::HTTP_OK, $response->getStatusCode() );
		$data = json_decode( $response->getContent(), true );
		$this->assertTrue( $data['success'] );
	}

	public function testPreviewWithLiveMode(): void
	{
		$controller = $this->createController();
		$request = new Request(
			content: json_encode( [
				'type' => 'task',
				'mode' => 'live',
				'config' => [
					'_class' => 'Set',
					'_ref' => 'live_test',
					'params' => [
						[ 'key' => 'mode', 'value' => 'live' ],
					],
				],
			] )
		);

		$executePreview = static::getContainer()->get( ExecutePreview::class );
		$response = $this->callHandlePreview( $controller, $request, $executePreview );

		$this->assertSame( Response::HTTP_OK, $response->getStatusCode() );
		$data = json_decode( $response->getContent(), true );
		$this->assertTrue( $data['success'] );
	}

	public function testPreviewWithVariablesPassedThrough(): void
	{
		$controller = $this->createController();
		$request = new Request(
			content: json_encode( [
				'type' => 'task',
				'config' => [
					'_class' => 'Set',
					'_ref' => 'var_test',
					'params' => [
						[ 'key' => 'from_var', 'value' => '{{ variables.test_var }}' ],
					],
				],
				'variables' => [ 'test_var' => 'injected_value' ],
			] )
		);

		$executePreview = static::getContainer()->get( ExecutePreview::class );
		$response = $this->callHandlePreview( $controller, $request, $executePreview );

		$data = json_decode( $response->getContent(), true );
		$this->assertTrue( $data['success'] );
		$this->assertSame( 'injected_value', $data['data']['Return']['from_var'] );
	}

	public function testPreviewWithRequestParamsPassedThrough(): void
	{
		$controller = $this->createController();
		$request = new Request(
			content: json_encode( [
				'type' => 'task',
				'config' => [
					'_class' => 'Set',
					'_ref' => 'request_params_test',
					'params' => [
						[ 'key' => 'from_params', 'value' => '{{ request.test_param }}' ],
					],
				],
				'requestParams' => [ 'test_param' => 'param_value' ],
				'requestQuery' => [ 'test_query' => 'query_value' ],
			] )
		);

		$executePreview = static::getContainer()->get( ExecutePreview::class );
		$response = $this->callHandlePreview( $controller, $request, $executePreview );

		$data = json_decode( $response->getContent(), true );
		$this->assertTrue( $data['success'] );
		$this->assertSame( 'param_value', $data['data']['Return']['from_params'] );
	}

	public function testPreviewSchemaReturnsSchemaForValidType(): void
	{
		$controller = $this->createController();
		$response = $controller->preview_schema( 'task' );

		$this->assertSame( Response::HTTP_OK, $response->getStatusCode() );
		$data = json_decode( $response->getContent(), true );
		$this->assertSame( 'task', $data['type'] );
		$this->assertArrayHasKey( 'fields', $data );
		$this->assertArrayHasKey( 'example', $data );
	}
}
