parameters:
  syncengine.icons:
    # Entities.
    connection: 'bi bi-cloud'
    automation: 'bi bi-command'
    flow: 'bi bi-diagram-3'
    step: 'bi bi-collection'
    storage: 'bi bi-database'
    trace: 'bi bi-bar-chart-steps'
    # Services.
    task: 'bi bi-list-task'
    webservice: 'bi bi-clouds'
    choose: 'bi bi-sign-intersection-y'
    send: 'bi bi-send'
    retrieve: 'bi bi-cloud-download'
    # Account
    account: 'bi bi-person-circle'
    account-edit: 'bi bi-person-gear'
    token: 'bi bi-shield-lock'
    restrict: 'bi bi-shield-slash'
    # System.
    dashboard: 'bi bi-speedometer2'
    condition: 'bi bi-check2-square'
    event: 'bi bi-lightning-charge'
    module: 'bi bi-plugin'
    schema: 'bi bi-diagram-2'
    system: 'bi bi-gear-wide-connected'
    system-environment: 'bi bi-motherboard'
    system-vault: 'bi bi-safe'
    system-processes: 'bi bi-terminal'
    system-processes-manager: 'bi bi-cpu-fill'
    system-processes-config: 'bi bi-cpu'
    system-info: 'bi bi-info-square'
    request: 'bi bi-send-arrow-down'
    response: 'bi bi-reply'
    variable: 'bi bi-braces-asterisk'
    tag: 'bi bi-braces'
    reboot: 'bi bi-bootstrap-reboot'
    # Run.
    event-cancel: 'x-octagon'
    event-success: 'exclamation-triangle'
    event-error: 'check-circle'
    preview: 'bi bi-play-circle'
    preview-live: 'bi bi-play-circle-fill'
    preview-scope: 'bi bi-skip-forward-circle'
    preview-scope-live: 'bi bi-skip-forward-circle-fill'
    # Edit.
    edit: 'bi bi-pencil-fill'
    set: 'bi bi-pencil-square'
    save: 'bi bi-save'
    update: 'bi bi-check-square'
    cross: 'bi bi-x-lg'
    plus: 'bi bi-plus-lg'
    check: 'bi bi-check-lg'
    delete: 'bi bi-trash-fill'
    remove: 'bi bi-dash-circle'
    grid: 'bi bi-input-cursor'
    input-select: 'bi bi-view-list'
    input-text: 'bi bi-input-cursor-text'
    input-textarea: 'bi bi-textarea-resize'
    # Generic.
    input: 'bi bi-box-arrow-in-right'
    output: 'bi bi-box-arrow-right'
    sort: 'bi bi-arrows-expand' # arrow-down-up # bi-chevron-bar-expand
    copy: 'bi bi-copy'
    help: 'bi bi-info-circle'
    upload: 'bi bi-upload'
    export: 'bi bi-upload'
    download: 'bi bi-download'
    import: 'bi bi-download'
    config: 'bi bi-gear'
    configured: 'bi bi-gear-fill'
    required: 'bi bi-asterisk'
    readonly: 'bi bi-shield-fill'
    code: 'bi bi-code'
    code-formatted: 'bi bi-chevron-expand'
    secret: 'bi bi-key'
    view: 'bi bi-eye-fill'
    visible: 'bi bi-eye'
    hidden: 'bi bi-eye-slash'
    clipboard: 'bi bi-clipboard'
    link: 'bi bi-link-45deg'
    reset: 'bi bi-arrow-counterclockwise'
    # Menu.
    menu-expand: 'bi bi-text-indent-left'
    menu-collapse: 'bi bi-text-indent-right'
    toolbar-menu: 'bi bi-three-dots-vertical'
    # Window.
    size-expand": 'bi bi-arrows-angle-expand'
    size-contract: 'bi bi-arrows-angle-contract'
    size-expand-x: 'bi bi-arrows-expand-vertical'
    size-contract-x: 'bi bi-arrows-collapse-vertical'
    size-expand-y: 'bi bi-arrows-expand'
    size-contract-y: 'bi bi-arrows-collapse'
    # Trace.
    trace-info: 'bi bi-info-circle'
    trace-iteration: 'bi bi-hash'
    trace-start: 'bi bi-calendar'
    trace-end: 'bi bi-calendar-check-fill'
    trace-duration: 'bi bi-stopwatch'
    trace-follow: 'bi bi-folder-symlink'
    # Collapsible
    accordion-close: 'bi bi-chevron-up'
    accordion-open: 'bi bi-chevron-down'
    # Theme
    theme-auto: 'bi bi-circle-half'
    theme-light: 'bi bi-sun-fill'
    theme-dark: 'bi bi-moon-stars-fill'
