SyncEngineCoreControllers:
  name_prefix: 'syncengine_'
  resource:
    path: ../src/Controller/
    namespace: SyncEngine\Controller
  type: attribute
SyncEngineAdminControllers:
  prefix: '/admin'
  name_prefix: 'syncengine_'
  resource:
    path: ../src/Controller/Admin/
    namespace: SyncEngine\Controller\Admin
  type: attribute
moduleControllers:
  prefix: '/dashboard'
  name_prefix: "dashboard_"
  resource:
    path: ../modules
    namespace: SyncEngine\Module
  type: attribute
