controllers:
  resource:
    path: ../src/Controller/
    namespace: SyncEngine\Controller
  type: attribute
moduleControllers:
  resource:
    path: ../modules
    namespace: SyncEngine\Module
  type: attribute
