
parameters:
  syncengine.dir.trace: '%syncengine.dir.root%/var/trace/test'

services:
    SyncEngine\Tests\Mock\Webservice\MockHttp:
        autowire: true
        autoconfigure: true
        tags: [ 'syncengine.model.webservice' ]
        shared: false
