<?php

namespace App\Webservice;

use App\Model\WebserviceModel;
use Symfony\Contracts\HttpClient\HttpClientInterface;

class Rest extends WebserviceModel
{
	public function __construct()
	{
		$this->type = 'rest';
		$this->name = 'REST';
		$this->description = 'Connect to a REST API';

		parent::__construct();
	}

	public function getAuthFields(): array
	{
		return [
			'host' => [
				'label' => 'Host',
				'type' => 'text',
			],
			'auth_type' => [
				'label' => 'Auth type',
				'type' => 'select',
				'choices'  => [
					'none' => 'None',
					'password' => 'Password',
					'key' => 'Key/Secret',
					'token' => 'Token',
				],
			],
			'username' => [
				'label' => 'Username',
				'type' => 'text',
				'conditionals' => [
					'auth_type' => 'password'
				],
			],
			'password' => [
				'label' => 'Password',
				'type' => 'password',
				'conditionals' => [
					'auth_type' => 'password'
				],
			],
			'token' => [
				'label' => 'Token',
				'type' => 'password',
				'conditionals' => [
					'auth_type' => 'token'
				],
			],
			'key' => [
				'label' => 'Key',
				'type' => 'password',
				'conditionals' => [
					'auth_type' => 'key'
				],
			],
			'secret' => [
				'label' => 'Secret',
				'type' => 'password',
				'conditionals' => [
					'auth_type' => 'key'
				],
			],
		];
	}

	public function getFields(): array
	{
		// @todo define task fields.
		// @todo allow override or even custom auth fields.
		return [
			'endpoint' => [
				'label' => 'Endpoint',
				'type' => 'text',
			]
		];
	}

	public function getClient( array $config = array() ): HttpClientInterface
	{
		$client = parent::getClient(); // TODO: Change the autogenerated stub

		$options = []; // @todo parse config.

		switch ( $config['auth_type'] ) {
			case 'password':
				$options['auto_basic'] = [ $config['username'], $config['password'] ];
			break;
			case 'key':
				$options['auto_basic'] = [ $config['key'], $config['secret'] ];
			break;
			case 'token':
				$options['query'] = [
					'token' => $config['token'],
				];
			break;
		}

		$client->withOptions( $options );
		return $client;
	}

	public function retrieve( array $config )
	{
		$client = $this->getClient( $config );
		// TODO: Implement retrieve() method.
	}

	public function send( array $config, $data )
	{
		$client = $this->getClient( $config );
		// TODO: Implement send() method.
	}
}
