name: Run Composer Install on Release

permissions:
  contents: write

on:
  release:
    types:
      - created

jobs:
  composer-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install JS dependencies
        run: npm ci

      - name: Build assets with Webpack Encore
        run: npm run build

      - name: Clear node_modules
        run: rm -r node_modules

      - name: Package the project
        run: zip -r release.zip . -x ".git/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-artifact
          path: release.zip

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release.zip
          asset_name: release.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
