name: Run Composer Install on Release

on:
  release:
    types:
      - created

jobs:
  composer-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Package the project
        run: zip -r release-full-build.zip . -x ".git/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-artifact
          path: release-full-build.zip

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release-full-build.zip
          asset_name: release-full-build.zip
          asset_content_type: application/zip

