name: 'PHP Unit Tests'
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'composer.json'
  push:
    branches:
      - 'master'
    paths:
      - 'src/**'
      - 'tests/**'
      - 'composer.json'

# Cancel unfinished builds if a new commit is made before it's completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: ['8.1']
    permissions:
      contents: write
      pull-requests: write
    steps:
      # Mandatory : fetch the current repository
      -   name: Checkout repository
          uses: actions/checkout@v3

      # To be faster, use cache system for the Composer
      -   name: Get Composer Cache Directory
          id: composer-dev-cache
          run: |
              echo "::set-output name=dir::$(composer config cache-files-dir)"
      -   name: Cache composer (vendor)
          uses: actions/cache@v3
          with:
              path: ${{ steps.composer-dev-cache.outputs.dir }}
              key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
              restore-keys: |
                  ${{ runner.os }}-composer-

      # Define the right PHP environment
      # https://github.com/shivammathur/setup-php (community)
      -   name: Environment for PHP
          uses: shivammathur/setup-php@v2
          with:
              php-version: ${{ matrix.php-versions }}
              extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
              tools: composer:v2
              coverage: none
          env:
              update: true

      # Ensure that composer.json is valid
#      -   name: Validate composer.json and composer.lock
#          run: composer validate

      # Log the PHP version in use, and copy the "prod" env file to the "local" env file
#      -   name: PHP utils
#          run: |
#              php -v
#              cp .env.prod .env.local

      # Install composer dependencies for dev.
      -   name: Composer install & dump-env
          run: |
              composer install

      # —— Symfony ——————————————————————————————————————————————————————————
#      -   name: Check Symfony requirements
#          run: vendor/bin/requirements-checker
#      -   name: Check the Symfony console
#          run: bin/console -V

      # Install composer dependencies, and dump env
      -   name: Run PHP Unit tests
          run: |
              cp .env.test .env
              cp phpunit.xml.dist phpunit.xml
              php bin/phpunit --stop-on-failure
