<?php

namespace SyncEngine\Command\Tmp;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use SyncEngine\Controller\DefaultController;

/**
 * @return void
 */
#[AsCommand(
	name: 'syncengine:execute:dev:update:rename-entity-date-columns',
	description: 'Fix trace data column since 2026-09-09',
)]
class FixDateColumnNamesCommand extends Command
{
	// @phpstan-ignore-next-line property.onlyWritten (Required to trigger DI container initialization)
	public function __construct( private DefaultController $controller )
	{
		parent::__construct();
	}

	protected function configure()
	{
		parent::configure(); // TODO: Change the autogenerated stub

		$this->addOption( 'rollback', null, InputOption::VALUE_OPTIONAL, 'Rollback the changes made by this command.', null );
	}

	protected function execute( InputInterface $input, OutputInterface $output ): int
	{
		try {
			$rollback = $input->getOption( 'rollback' );

			if ( $rollback ) {
				$output->writeln( '<comment>Rolling back changes...</comment>' );
				$em = $this->controller::getEntityManager();

				foreach ( [ 'trace', 'connection', 'automation', 'flow', 'routine', 'storage' ] as $entity ) {
					$em->getConnection()->executeStatement('ALTER TABLE '.$entity.' CHANGE `created_at` `created` LONGTEXT NOT NULL');
					$em->getConnection()->executeStatement('ALTER TABLE '.$entity.' CHANGE `updated_at` `modified` LONGTEXT NOT NULL');
				}

				$em->getConnection()->executeStatement('ALTER TABLE api_token CHANGE `expires_at` `expires` LONGTEXT NOT NULL');

				$output->writeln( '<info>Rollback completed successfully.</info>' );
				return Command::SUCCESS;
			}

			$em = $this->controller::getEntityManager();

			foreach ( [ 'trace', 'connection', 'automation', 'flow', 'routine', 'storage' ] as $entity ) {
				$em->getConnection()->executeStatement('ALTER TABLE '.$entity.' CHANGE `created` `created_at` LONGTEXT NOT NULL');
				$em->getConnection()->executeStatement('ALTER TABLE '.$entity.' CHANGE `modified` `updated_at` LONGTEXT NOT NULL');
			}

			$em->getConnection()->executeStatement('ALTER TABLE api_token CHANGE `expires` `expires_at` LONGTEXT NOT NULL');

		} catch (\Exception $e) {
			$output->writeln('<error>Error: ' . $e->getMessage() . '</error>');
			return Command::FAILURE;
		}

		return Command::SUCCESS;
	}
}
