<?php

namespace SyncEngine\Command\Tmp;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use SyncEngine\Controller\DefaultController;

/**
 * @return void
 */
#[AsCommand(
	name: 'syncengine:execute:dev:update:rename-entity-date-columns',
	description: 'Fix trace data column since 2026-09-09',
)]
class FixDateColumnNamesCommand extends Command
{
	// @phpstan-ignore-next-line property.onlyWritten (Required to trigger DI container initialization)
	public function __construct(
		private EntityManagerInterface $entityManager,
		#[Autowire('%syncengine.db.table_prefix%')] private string $tablePrefix
	) {
		parent::__construct();
	}

	protected function configure()
	{
		parent::configure(); // TODO: Change the autogenerated stub

		$this->addOption( 'rollback', null, InputOption::VALUE_OPTIONAL, 'Rollback the changes made by this command.', null );
	}

	protected function execute( InputInterface $input, OutputInterface $output ): int
	{
		$connection = $this->entityManager->getConnection();

		try {
			$rollback = $input->getOption( 'rollback' );

			if ( $rollback ) {
				$output->writeln( '<comment>Rolling back changes...</comment>' );

				foreach ( [ 'trace', 'connection', 'automation', 'flow', 'routine', 'storage' ] as $entity ) {
					$table = $this->tablePrefix . $entity;
					$connection->executeStatement('ALTER TABLE '.$table.' CHANGE `created_at` `created` LONGTEXT NOT NULL');
					$connection->executeStatement('ALTER TABLE '.$table.' CHANGE `updated_at` `modified` LONGTEXT NOT NULL');
				}

				$connection->executeStatement('ALTER TABLE '.$this->tablePrefix.'api_token CHANGE `expires_at` `expires` LONGTEXT NOT NULL');

				$output->writeln( '<info>Rollback completed successfully.</info>' );
				return Command::SUCCESS;
			}

			foreach ( [ 'trace', 'connection', 'automation', 'flow', 'routine', 'storage' ] as $entity ) {
				$table = $this->tablePrefix . $entity;
				$connection->executeStatement('ALTER TABLE '.$table.' CHANGE `created` `created_at` LONGTEXT NOT NULL');
				$connection->executeStatement('ALTER TABLE '.$table.' CHANGE `modified` `updated_at` LONGTEXT NOT NULL');
			}

			$connection->executeStatement('ALTER TABLE '.$this->tablePrefix.'api_token CHANGE `expires` `expires_at` LONGTEXT NOT NULL');

		} catch (\Exception $e) {
			$output->writeln('<error>Error: ' . $e->getMessage() . '</error>');
			return Command::FAILURE;
		}

		return Command::SUCCESS;
	}
}
